services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # command: sh -c "npm install && npm run start"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - HOST=0.0.0.0
    command: sh -c "npm install && npm run dev"
